import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1784024089885 implements MigrationInterface {
    name = 'Baseline1784024089885'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."user_chat_roles_role_enum" AS ENUM('ADMIN', 'SUPERVISOR', 'CONTROLLER', 'ACCOUNTANT', 'BANK_CLIENT', 'CLIENT', 'BOT')`);
        await queryRunner.query(`CREATE TABLE "user_chat_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "chatId" bigint NOT NULL, "chatType" character varying(32) NOT NULL, "role" "public"."user_chat_roles_role_enum" NOT NULL DEFAULT 'ACCOUNTANT', "chatTitle" character varying, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_5492c1fef0e348080070fde17cd" UNIQUE ("userId", "chatId"), CONSTRAINT "PK_a09624cf71cbb8cb98937ad15fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message_responses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "originalMessageId" uuid NOT NULL, "responseMessageId" character varying NOT NULL, "responderId" character varying NOT NULL, "responseTime" TIMESTAMP NOT NULL, "responseTimeSeconds" integer, "responseText" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f50ce8cd93054476eae3e9e1aef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."message_logs_direction_enum" AS ENUM('INCOMING', 'OUTGOING')`);
        await queryRunner.query(`CREATE TYPE "public"."message_logs_senderroleatmoment_enum" AS ENUM('ADMIN', 'SUPERVISOR', 'CONTROLLER', 'ACCOUNTANT', 'BANK_CLIENT', 'CLIENT', 'BOT')`);
        await queryRunner.query(`CREATE TYPE "public"."message_logs_answerdetectionmethod_enum" AS ENUM('REPLY', 'TIME_WINDOW_SIMPLE', 'AI_CONFIRMED', 'SYSTEM_TIMEOUT')`);
        await queryRunner.query(`CREATE TYPE "public"."message_logs_sttstatus_enum" AS ENUM('PENDING', 'PROCESSING', 'DOWNLOADING_FILE', 'SENDING_TO_STT', 'COMPLETED', 'FAILED_QUEUE', 'FAILED_DOWNLOAD', 'FAILED_STT_SERVICE', 'FAILED_UPDATE_LOG', 'FAILED_UNKNOWN', 'FAILED_STT_NO_RESPONSE', 'FAILED_NO_FILE_LINK', 'NOT_APPLICABLE')`);
        await queryRunner.query(`CREATE TYPE "public"."message_logs_llmanalysisstatus_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED_QUEUE', 'FAILED_LLM_SERVICE', 'FAILED_LLM_PROCESSING', 'FAILED_UPDATE_LOG', 'FAILED_UNKNOWN', 'NOT_APPLICABLE')`);
        await queryRunner.query(`CREATE TABLE "message_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "telegramMessageId" bigint, "chatId" bigint NOT NULL, "text" text, "direction" "public"."message_logs_direction_enum", "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "rawMessage" jsonb, "senderRoleAtMoment" "public"."message_logs_senderroleatmoment_enum", "isQuestion" boolean NOT NULL DEFAULT false, "questionStatusTemp" character varying(20), "answeredByMessageId" bigint, "responseTimeSeconds" integer, "answerDetectionMethod" "public"."message_logs_answerdetectionmethod_enum", "transcribedText" text, "attachmentType" character varying(50), "attachmentFileId" character varying(255), "attachmentFileUniqueId" character varying(255), "attachmentDurationSeconds" integer, "sttStatus" "public"."message_logs_sttstatus_enum" DEFAULT 'NOT_APPLICABLE', "llmAnalysisStatus" "public"."message_logs_llmanalysisstatus_enum" DEFAULT 'NOT_APPLICABLE', "llmPromptType" character varying(100), "llmAnalysisPrompt" text, "llmAnalysisResponse" text, "llmStructuredResponse" jsonb, "userId" uuid NOT NULL, "answeredByUserId" uuid, CONSTRAINT "PK_f0aae0d876a96fa1da0a1b97444" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ce499903088fd9f1dd56e447fc" ON "message_logs" ("telegramMessageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d5f99823a21761fe4e49518999" ON "message_logs" ("chatId") `);
        await queryRunner.query(`CREATE TYPE "public"."kpi_scores_role_enum" AS ENUM('ADMIN', 'SUPERVISOR', 'CONTROLLER', 'ACCOUNTANT', 'BANK_CLIENT', 'CLIENT', 'BOT')`);
        await queryRunner.query(`CREATE TABLE "kpi_scores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" "public"."kpi_scores_role_enum" NOT NULL, "periodStart" date NOT NULL, "periodEnd" date NOT NULL, "responseTimeScore" numeric(5,2) NOT NULL DEFAULT '0', "totalQuestions" integer NOT NULL DEFAULT '0', "onTimeResponses" integer NOT NULL DEFAULT '0', "lateResponses" integer NOT NULL DEFAULT '0', "reportSubmissionScore" numeric(5,2) NOT NULL DEFAULT '0', "totalReports" integer NOT NULL DEFAULT '0', "onTimeReports" integer NOT NULL DEFAULT '0', "lateReports" integer NOT NULL DEFAULT '0', "attendanceScore" numeric(5,2) NOT NULL DEFAULT '0', "totalWorkDays" integer NOT NULL DEFAULT '0', "onTimeArrivals" integer NOT NULL DEFAULT '0', "lateArrivals" integer NOT NULL DEFAULT '0', "responseQualityScore" numeric(5,2) NOT NULL DEFAULT '0', "finalScore" numeric(5,2) NOT NULL DEFAULT '0', "bonusAmount" numeric(10,2) NOT NULL DEFAULT '0', "penaltyAmount" numeric(10,2) NOT NULL DEFAULT '0', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, CONSTRAINT "PK_a56b4e369d51e69f9f1f54d082b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2785d3cec73fa17e9804814011" ON "kpi_scores" ("userId", "periodStart", "periodEnd") `);
        await queryRunner.query(`CREATE TYPE "public"."kpi_reports_status_enum" AS ENUM('draft', 'published', 'archived')`);
        await queryRunner.query(`CREATE TYPE "public"."kpi_reports_userrole_enum" AS ENUM('ADMIN', 'SUPERVISOR', 'CONTROLLER', 'ACCOUNTANT', 'BANK_CLIENT', 'CLIENT', 'BOT')`);
        await queryRunner.query(`CREATE TABLE "kpi_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "startDate" date NOT NULL, "endDate" date NOT NULL, "status" "public"."kpi_reports_status_enum" NOT NULL DEFAULT 'draft', "metrics" jsonb NOT NULL DEFAULT '{}', "totalScore" numeric(5,2) NOT NULL DEFAULT '0', "bonusAmount" numeric(10,2), "penaltyAmount" numeric(10,2), "notes" text, "userId" uuid, "userRole" "public"."kpi_reports_userrole_enum", "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "publishedAt" TIMESTAMP, "archivedAt" TIMESTAMP, CONSTRAINT "PK_13bdee28fa88d817961ba077821" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8a6bb61c15b68b3aa2f07e1b1a" ON "kpi_reports" ("userId", "startDate", "endDate") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "telegramId" bigint NOT NULL, "username" character varying, "firstName" character varying, "lastName" character varying, "isBot" boolean NOT NULL DEFAULT false, "languageCode" character varying, "isActive" boolean NOT NULL DEFAULT true, "baseSalary" numeric(10,2) NOT NULL DEFAULT '0', CONSTRAINT "UQ_df18d17f84763558ac84192c754" UNIQUE ("telegramId"), CONSTRAINT "UQ_df18d17f84763558ac84192c754" UNIQUE ("telegramId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "chatId" bigint NOT NULL, "sessionData" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e93e031a5fed190d4789b6bfd83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_eeca38dd9cf55a7fa85e9179d8" ON "user_sessions" ("userId", "chatId") `);
        await queryRunner.query(`CREATE TYPE "public"."report_types_frequency_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'ADHOC')`);
        await queryRunner.query(`CREATE TYPE "public"."report_types_responsibleroles_enum" AS ENUM('ADMIN', 'SUPERVISOR', 'CONTROLLER', 'ACCOUNTANT', 'BANK_CLIENT', 'CLIENT', 'BOT')`);
        await queryRunner.query(`CREATE TABLE "report_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "frequency" "public"."report_types_frequency_enum" NOT NULL DEFAULT 'ADHOC', "deadlineRule" character varying(255), "responsibleRoles" "public"."report_types_responsibleroles_enum" array, "fileTemplateHint" character varying(255), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cf77ff01fa1da1f9978995e67c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f9bfaf722e6cbd5eb9c6dab6f2" ON "report_types" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."report_submissions_status_enum" AS ENUM('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'SUBMITTED', 'DRAFT')`);
        await queryRunner.query(`CREATE TABLE "report_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" text, "description" text, "telegramFileId" character varying(255), "fileUrl" character varying(1000), "status" "public"."report_submissions_status_enum" NOT NULL DEFAULT 'SUBMITTED', "reviewComment" text, "submittedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "reportPeriodStartDate" date, "reportPeriodEndDate" date, "chatId" bigint, "submittedByUserId" uuid NOT NULL, "reportTypeId" uuid NOT NULL, "reviewedByUserId" uuid, CONSTRAINT "PK_8fb46f2835eb89c8fed733eaf9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_530a3ea85dfc0599aec088b1d8" ON "report_submissions" ("reportTypeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca38db03acabf81971b2d91202" ON "report_submissions" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."report_logs_status_enum" AS ENUM('SUBMITTED', 'ON_TIME', 'LATE', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "report_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "chatId" bigint NOT NULL, "messageId" bigint NOT NULL, "fileId" character varying(255), "fileName" character varying(255), "submissionNotes" text, "status" "public"."report_logs_status_enum" NOT NULL DEFAULT 'SUBMITTED', "submissionTimestamp" TIMESTAMP NOT NULL DEFAULT now(), "deadlineTimestamp" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "submittedByUserId" uuid NOT NULL, "reportTypeId" uuid NOT NULL, CONSTRAINT "PK_242e8e0f9c2689f09aeaf00e67b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5cebf9b92cfab120f1c14f344e" ON "report_logs" ("chatId") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('info', 'warning', 'danger', 'success')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('pending', 'sent', 'read', 'failed')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "message" text NOT NULL, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'info', "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'pending', "metadata" jsonb, "actionUrl" character varying, "userId" uuid NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "sentAt" TIMESTAMP, "readAt" TIMESTAMP, "error" text, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."kpi_definitions_frequency_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', 'ONE_TIME')`);
        await queryRunner.query(`CREATE TYPE "public"."kpi_definitions_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'ARCHIVED', 'PENDING_APPROVAL')`);
        await queryRunner.query(`CREATE TABLE "kpi_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" text, "metricName" character varying(50) NOT NULL, "metricUnit" character varying(20) NOT NULL, "targetValue" numeric(10,2), "frequency" "public"."kpi_definitions_frequency_enum" NOT NULL DEFAULT 'MONTHLY', "status" "public"."kpi_definitions_status_enum" NOT NULL DEFAULT 'PENDING_APPROVAL', "startDate" date, "endDate" date, "createdById" uuid NOT NULL, "approvedById" uuid, "additionalConfig" jsonb, CONSTRAINT "PK_c68b23412c3d914579ce17c1d24" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fc951d55c388ddcc6083339210" ON "kpi_definitions" ("createdById") `);
        await queryRunner.query(`CREATE TYPE "public"."attendance_logs_status_enum" AS ENUM('CHECKED_IN', 'CHECKED_OUT', 'ABSENT_WITH_REASON', 'ABSENT_WITHOUT_REASON', 'ON_LEAVE', 'SICK_LEAVE')`);
        await queryRunner.query(`CREATE TABLE "attendance_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" date NOT NULL, "checkInTime" TIMESTAMP, "checkInNotes" character varying(255), "checkOutTime" TIMESTAMP, "checkOutNotes" character varying(255), "status" "public"."attendance_logs_status_enum", "durationMinutes" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, CONSTRAINT "PK_e78c28cf950bd06d614ae09f26b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_64776b55829e928eff680c997f" ON "attendance_logs" ("date") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f50bf75feabe804b6c034abf61" ON "attendance_logs" ("userId", "date") `);
        await queryRunner.query(`ALTER TABLE "user_chat_roles" ADD CONSTRAINT "FK_c85200ead264a6f37b45a9da0fc" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_responses" ADD CONSTRAINT "FK_26cbad80491534329b1bdf91e40" FOREIGN KEY ("originalMessageId") REFERENCES "message_logs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD CONSTRAINT "FK_b1ca317a226af3aef10c2a24d83" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_logs" ADD CONSTRAINT "FK_dd49aa8da3a86f3aadb3bfd6084" FOREIGN KEY ("answeredByUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_scores" ADD CONSTRAINT "FK_25b9a6308c011cddfed06e29a5a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_reports" ADD CONSTRAINT "FK_295617e68febbc428b91aab6d47" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "FK_55fa4db8406ed66bc7044328427" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_submissions" ADD CONSTRAINT "FK_71d2db4e3c943201dbc436a729c" FOREIGN KEY ("submittedByUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_submissions" ADD CONSTRAINT "FK_530a3ea85dfc0599aec088b1d8c" FOREIGN KEY ("reportTypeId") REFERENCES "report_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_submissions" ADD CONSTRAINT "FK_d7681a27309b78dad530a415c01" FOREIGN KEY ("reviewedByUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_logs" ADD CONSTRAINT "FK_80b3a6aedfdda9a69f654487b95" FOREIGN KEY ("submittedByUserId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_logs" ADD CONSTRAINT "FK_d6a39d4c6b97082e7ff69a88417" FOREIGN KEY ("reportTypeId") REFERENCES "report_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_definitions" ADD CONSTRAINT "FK_fc951d55c388ddcc60833392100" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpi_definitions" ADD CONSTRAINT "FK_b5de67f3b2644962f48843dad36" FOREIGN KEY ("approvedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_logs" ADD CONSTRAINT "FK_70e413337da7ede7ec82c03cd67" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "attendance_logs" DROP CONSTRAINT "FK_70e413337da7ede7ec82c03cd67"`);
        await queryRunner.query(`ALTER TABLE "kpi_definitions" DROP CONSTRAINT "FK_b5de67f3b2644962f48843dad36"`);
        await queryRunner.query(`ALTER TABLE "kpi_definitions" DROP CONSTRAINT "FK_fc951d55c388ddcc60833392100"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "report_logs" DROP CONSTRAINT "FK_d6a39d4c6b97082e7ff69a88417"`);
        await queryRunner.query(`ALTER TABLE "report_logs" DROP CONSTRAINT "FK_80b3a6aedfdda9a69f654487b95"`);
        await queryRunner.query(`ALTER TABLE "report_submissions" DROP CONSTRAINT "FK_d7681a27309b78dad530a415c01"`);
        await queryRunner.query(`ALTER TABLE "report_submissions" DROP CONSTRAINT "FK_530a3ea85dfc0599aec088b1d8c"`);
        await queryRunner.query(`ALTER TABLE "report_submissions" DROP CONSTRAINT "FK_71d2db4e3c943201dbc436a729c"`);
        await queryRunner.query(`ALTER TABLE "user_sessions" DROP CONSTRAINT "FK_55fa4db8406ed66bc7044328427"`);
        await queryRunner.query(`ALTER TABLE "kpi_reports" DROP CONSTRAINT "FK_295617e68febbc428b91aab6d47"`);
        await queryRunner.query(`ALTER TABLE "kpi_scores" DROP CONSTRAINT "FK_25b9a6308c011cddfed06e29a5a"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP CONSTRAINT "FK_dd49aa8da3a86f3aadb3bfd6084"`);
        await queryRunner.query(`ALTER TABLE "message_logs" DROP CONSTRAINT "FK_b1ca317a226af3aef10c2a24d83"`);
        await queryRunner.query(`ALTER TABLE "message_responses" DROP CONSTRAINT "FK_26cbad80491534329b1bdf91e40"`);
        await queryRunner.query(`ALTER TABLE "user_chat_roles" DROP CONSTRAINT "FK_c85200ead264a6f37b45a9da0fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f50bf75feabe804b6c034abf61"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64776b55829e928eff680c997f"`);
        await queryRunner.query(`DROP TABLE "attendance_logs"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_logs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc951d55c388ddcc6083339210"`);
        await queryRunner.query(`DROP TABLE "kpi_definitions"`);
        await queryRunner.query(`DROP TYPE "public"."kpi_definitions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."kpi_definitions_frequency_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5cebf9b92cfab120f1c14f344e"`);
        await queryRunner.query(`DROP TABLE "report_logs"`);
        await queryRunner.query(`DROP TYPE "public"."report_logs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca38db03acabf81971b2d91202"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_530a3ea85dfc0599aec088b1d8"`);
        await queryRunner.query(`DROP TABLE "report_submissions"`);
        await queryRunner.query(`DROP TYPE "public"."report_submissions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9bfaf722e6cbd5eb9c6dab6f2"`);
        await queryRunner.query(`DROP TABLE "report_types"`);
        await queryRunner.query(`DROP TYPE "public"."report_types_responsibleroles_enum"`);
        await queryRunner.query(`DROP TYPE "public"."report_types_frequency_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eeca38dd9cf55a7fa85e9179d8"`);
        await queryRunner.query(`DROP TABLE "user_sessions"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a6bb61c15b68b3aa2f07e1b1a"`);
        await queryRunner.query(`DROP TABLE "kpi_reports"`);
        await queryRunner.query(`DROP TYPE "public"."kpi_reports_userrole_enum"`);
        await queryRunner.query(`DROP TYPE "public"."kpi_reports_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2785d3cec73fa17e9804814011"`);
        await queryRunner.query(`DROP TABLE "kpi_scores"`);
        await queryRunner.query(`DROP TYPE "public"."kpi_scores_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5f99823a21761fe4e49518999"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce499903088fd9f1dd56e447fc"`);
        await queryRunner.query(`DROP TABLE "message_logs"`);
        await queryRunner.query(`DROP TYPE "public"."message_logs_llmanalysisstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."message_logs_sttstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."message_logs_answerdetectionmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."message_logs_senderroleatmoment_enum"`);
        await queryRunner.query(`DROP TYPE "public"."message_logs_direction_enum"`);
        await queryRunner.query(`DROP TABLE "message_responses"`);
        await queryRunner.query(`DROP TABLE "user_chat_roles"`);
        await queryRunner.query(`DROP TYPE "public"."user_chat_roles_role_enum"`);
    }

}
