export const SUPABASE_SCHEMA_SQL = `
-- 1. Hujjatlar jadvali (Documents)
create table if not exists documents (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category text default 'BHMS',
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Chat tarixi jadvali (Chat History)
create table if not exists chat_history (
  id bigint generated by default as identity primary key,
  role text not null,
  text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Row Level Security (RLS) ni yoqish (Xavfsizlik uchun)
alter table documents enable row level security;
alter table chat_history enable row level security;

-- 4. Ruxsatlarni ochish (Hamma o'qiy olishi va yoza olishi uchun - Prototip rejimi)
create policy "Enable all access for documents" on documents for all using (true) with check (true);
create policy "Enable all access for chat_history" on chat_history for all using (true) with check (true);
`;